name: Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
    
      - name: Install Dotnet Tools
        run: dotnet tool restore
        
      - name: Run Build
        run: dotnet ib build